### ISSUE TITLE
FCM registration buttons remains disabled

### ISSUE THREAD

**Issue by sysmesh** [samapraku/lhc_gcm_extension#1]
Hi,
First - great tool and great work!

I've installed the latest version of LiveHelperChat and your extension on it.
I've updated the settings.ini and cleared the cache and also ensured the folder is /extension/gcm/ and that it is readable via http and https.

Yet the "push notifications" -> "register FCM" remains disabled on the android app.
Is there a know issue with the latest version? any recommended fix for this?

Thanks!

**Comment by samapraku** [comment]
Hello sysmesh,

Thank you for trying it out. 

I'll be releasing a new version of the extension and the android app in few hours.

The registration will now be handled by app and not manually.

**Comment by sysmesh** [comment]
Wow thanks!!!

**Comment by samapraku** [comment]
@sysmesh  the new version has been released in playstore as well as the extension here.

You just need to replace all the contents of the old gcm folder with this new one. Check the readme for instructions

**Comment by sysmesh** [comment]
Thanks Man! You rock!
I've installed the new app and extension code and it seems good now.
