### ISSUE TITLE
Web admin forced to logout after enabling GCM

### ISSUE THREAD

**Issue by lutsifer** [samapraku/lhc_gcm_extension#3]
Hello,

I have a weird problem.

After enabling the GCM extension whenever a user opens a chat session - my phone application gets a notification - great, however, my web (admin) access immediately is being forced to logout. If I remove GCM from the extensions array in settings - it continues working just fine, but no notifications to the app.
This happens every time I receive a push notification in the app.
Aside from this - everything else works just fine...

Please advise?

**Comment by samapraku** [comment]
Hello,

which version of main LIvehelper chat web application are you using? Web app, not mobile app.

**Comment by lutsifer** [comment]
Hey, thank you for the fast response.
It is hard to say, but I guess it is the latest:)
https://github.com/remdex/livehelperchat/archive/master.zip
I did the download this morning...

**Comment by lutsifer** [comment]
It is tested both with PHP 7.0 and 5.6, the same result.

**Comment by samapraku** [comment]
Hi, 
I have updated the version on my LHC web app to the latest on the the website and it is working correctly with the extension. 

I haven't been able to reproduce the error.

If you haven't already, could you try cleaning the application cache and enabling/disabling the cache to see if the issue still persists?

Regards

**Comment by lutsifer** [comment]
Nope, no result at all...

However, I was able to detect the logout message, it says:

> This window will be automatically refreshed in 2 seconds due to a version update.

**Comment by lutsifer** [comment]
Is there other files updated from the gcm other then 

> extension/gcm/settings/settings.ini.php

And even more importantly, why on each new chat request?

**Comment by samapraku** [comment]
The settings.ini.php is only updated once to register your device to receive push notifications. It is not updated on each new chat request and no other file is updated. 

The message you are seeing is from LHC itself and not from the extension. 

I still cannot reproduce the issue

**Comment by lutsifer** [comment]
Finally... I remember reading somewhere that there was a problem using same browser to log in twice. 
So I decided to open this time my web admin inside Firefox (I was using Chrome before). And it worked!
Not sure, but I guess you use some kind of hybrid library for the app like ionic? And the browser window inside the app is Chrome. It sounds strange but... I have no other explanation why this time it worked...

**Comment by lutsifer** [comment]
If I am correct then using another admin account inside chrome should do the trick for me...

**Comment by samapraku** [comment]
> Finally... I remember reading somewhere that there was a problem using same browser to log in twice.
> So I decided to open this time my web admin inside Firefox (I was using Chrome before). And it worked!
> Not sure, but I guess you use some kind of hybrid library for the app like ionic? And the browser window inside the app is Chrome. It sounds strange but... I have no other explanation why this time it worked...

Great that it is working. However, I'm not sure about the exact role of the extension in causing this issue. 

The app is built with Flutter. The source code is available in my repositories:
https://github.com/samapraku/lhc_messenger

**Comment by lutsifer** [comment]
Hm not familiar with this library... anyway, I will try to check the browser login issue and will test more with another account tomorrow.
I'll update the ticket as soon as I have more info.
Thank you!

**Comment by lutsifer** [comment]
Solved. I was stupid enough to test from the same browser window where the admin user was logged in. Testing from another browser solved the problem. The previous versions of LHC had better session naming I guess and the problem was not presented. I am closing this issue.
