### ISSUE TITLE
PHP Errors after installation and blank page in LHC

### ISSUE THREAD

**Issue by RolandSM** [samapraku/lhc_gcm_extension#4]
Hello,

I would try your android app but after installing the gcm in extensions like described an activating, lhc shows only a blank page.
In error.log there are many errors like:

`[Sun Dec 29 12:41:09.922857 2019] [fcgid:warn] [pid 26768] [client xx.xx.xx.xx:44928] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'erLhcoreClassChatEventDispatcher' not found in /var/www/xxx/web/extension/gcm/bootstrap/bootstrap.php:20, referer: https://xx.de/index.php/site_admin/system/configuration`

**Comment by samapraku** [comment]
Hello,

sorry about the issue you are experiencing.

Have you tried clearing the cache for the main web application? 

Under LHC Setings -> System > Clean Cache

**Comment by RolandSM** [comment]
Hello,

not possible because blank page after activating the extension.

But yes, I tried it also one time with cache clean before activating with same result.

In the forum on page 5 is the same issue but no solution?

**Comment by samapraku** [comment]
Hello, 

sorry for the late reply. I still cannot find what could be the cause of the error.

the OP in the forum post fixed the issue himself. I think it was something to do with his installation or server but I don't remember.

If it's possible, could you do a separate clean installation and add the extension so it to help us troubleshoot?

Thanks

**Comment by RolandSM** [comment]
Hello,

I found my error, updates I do since years only with rsync.
So in new LHC versions exists files & folders that was not syncing to my installation.

I wonder how it could work.

But now, on a fresh file base, all works, also with login from android app.
